version: "3.5"
services:
  web:
    image: nginx
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
      replicas: 5
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webserver

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webserver

networks:
  webserver: 
