print("Giropos Strigus Girus")
print("Qual o seu nome?:" )
nome = input()
print ("Prazer em te conhecer, "+ nome)
tamanho = str(len(nome))
print("O tamanho do deu nome é: " + tamanho)
print("Qual a sua idade?:")
idade = input()
print('voce ira fazer ' +str(int(idade) +1) +'em um ano')
